# -*- coding: utf-8 -*-
"""brain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPGBaV_Ofu_-wr-53gg7k3jd8eIpG0cB
"""

from dataclasses import dataclass, field
from typing import Dict, List, Any
import re

from dataclasses import dataclass, field
from typing import Dict, List, Any
import re


@dataclass
class QueryUnderstanding:
    original_query: str
    intent: str
    goal: str
    complexity: float
    entities: List[str] = field(default_factory=list)
    requirements: List[str] = field(default_factory=list)
    constraints: List[str] = field(default_factory=list)
    capabilities: List[str] = field(default_factory=list) # Added this line
    needs_tools: bool = False
    needs_multiple_agents: bool = False


@dataclass
class BrainDecision:
    understanding: QueryUnderstanding
    recommended_agents: List[str]
    reasoning: List[str]
    confidence: float

class IntelligenceBrain:

    def __init__(self):

        self.name = "Intelligence Brain"
        self.version = "1.1"



        self.intent_signals = {

            "MACHINE_LEARNING": [
                "machine learning",
                "machine-learning",
                "ml model",
                "ml",
                "model training",
                "train model",
                "train a model",
                "classification",
                "regression",
                "prediction",
                "predict",
                "neural network",
                "deep learning",
                "accuracy",
                "precision",
                "recall",
                "f1 score",
                "overfitting",
                "underfitting",
                "feature engineering",
                "hyperparameter"
            ],

            "DATA_ANALYSIS": [
                "dataset",
                "data analysis",
                "data analyze",
                "analyze data",
                "analyse data",
                "eda",
                "exploratory data analysis",
                "csv",
                "dataframe",
                "statistics",
                "statistical analysis",
                "missing values",
                "outliers"
            ],

            "CODING": [
                "code",
                "coding",
                "program",
                "programming",
                "python",
                "javascript",
                "java",
                "html",
                "css",
                "function",
                "class",
                "script",
                "debug",
                "bug",
                "exception",
                "error"
            ],

            "RESEARCH": [
                "research",
                "latest",
                "recent",
                "current",
                "news",
                "find information",
                "search",
                "investigate",
                "study"
            ],

           "REASONING": [

                 "why",
                 "explain",
                 "explanation",
                 "reason",
                 "compare",
                 "comparison",
                 "difference",
                 "versus",
                 "vs",
                 "pros and cons"

           ],
        }



        self.requirement_signals = {

            "implementation": [
                "build",
                "create",
                "develop",
                "implement",
                "make",
                "write code",
                "develop a"
            ],

            "optimization": [
                "improve",
                "improve accuracy",
                "increase accuracy",
                "optimize",
                "optimization",
                "performance",
                "tune",
                "fine tune",
                "fine-tune",
                "reduce error",
                "better accuracy"
            ],

            "analysis": [
                     "analyze",
                 "analyse",
                 "analysis",
                 "eda",
                 "explore",
                 "exploratory"
            ],

            "explanation": [
                    "explain",
                    "explanation",
                    "why",
                    "how does",
                    "what is",
                    "understand"

            ],

            "debugging": [
                "debug",
                "debugging",
                "fix error",
                "fix bug",
                "error",
                "bug",
                "exception",
                "not working",
                "doesn't work",
                "does not work"
            ],

            "research": [
                "research",
                "latest",
                "recent",
                "current",
                "news",
                "search",
                "find information",
                "investigate"
            ],

            "comparison": [
                "compare",
                "comparison",
                "difference",
                "versus",
                "vs",
                "better than"
            ],

            "prediction": [
                "predict",
                "prediction",
                "forecast",
                "forecasting"
            ]
        }



        self.known_entities = [

            "python",
            "javascript",
            "java",
            "c",
            "c++",
            "html",
            "css",

            "tensorflow",
            "pytorch",
            "keras",
            "scikit-learn",
            "sklearn",

            "pandas",
            "numpy",
            "opencv",

            "machine learning",
            "deep learning",
            "neural network",
            "llm",
            "rag",

            "csv",
            "json",
            "sql",
            "mysql",

            "faiss",
            "langchain"
        ]


        self.agent_capabilities = {

            "ResearchAgent": {
                "research"
            },

            "CodingAgent": {
                "implementation",
                "debugging"
            },

            "DataAnalysisAgent": {
                "analysis"
            },

            "MLAgent": {
                "implementation",
                "optimization",
                "prediction"
            },

            "ReasoningAgent": {
                "explanation",
                "comparison"
            },

            "CriticAgent": {
                "verification",
                "quality_control"
            }
        }


    def think(self, query: str) -> BrainDecision:

        if not isinstance(query, str):
            raise TypeError("Query must be a string.")

        query = query.strip()

        if not query:
            raise ValueError("Query cannot be empty.")

        understanding = self.understand(query)

        agents = self.select_agents(understanding)

        reasoning = self.generate_reasoning(
            understanding,
            agents
        )

        confidence = self.calculate_confidence(
            understanding,
            agents
        )

        return BrainDecision(
            understanding=understanding,
            recommended_agents=agents,
            reasoning=reasoning,
            confidence=confidence
        )


    def understand(self, query: str) -> QueryUnderstanding:

        normalized_query = self.normalize(query)

        intent = self.detect_intent(normalized_query)

        goal = self.extract_goal(query)

        entities = self.extract_entities(normalized_query)

        requirements = self.extract_requirements(
            normalized_query
        )

        capabilities = self.detect_capabilities(
            normalized_query
        )

        constraints = self.extract_constraints(
            normalized_query
        )

        complexity = self.calculate_complexity(
            normalized_query,
            requirements,
            capabilities
        )

        needs_tools = self.detect_tool_requirement(
            normalized_query
        )

        needs_multiple_agents = (
            len(capabilities) >= 2
            or len(requirements) >= 2
            or complexity >= 0.60
        )

        return QueryUnderstanding(

            original_query=query,

            intent=intent,

            goal=goal,

            complexity=complexity,

            entities=entities,

            requirements=requirements,

            constraints=constraints,

            capabilities=capabilities,

            needs_tools=needs_tools,

            needs_multiple_agents=needs_multiple_agents
        )


    def normalize(self, query: str) -> str:

        query = query.lower().strip()


        query = re.sub(
            r"\s+",
            " ",
            query
        )

        return query



    def detect_intent(self, query: str) -> str:

        scores = {}

        for intent, signals in self.intent_signals.items():

            score = 0

            for signal in signals:

                if self.signal_matches(
                    query,
                    signal
                ):
                    score += self.signal_weight(
                        signal
                    )

            scores[intent] = score


        if (
            "machine learning" in query
            or "ml model" in query
            or "machine-learning" in query
        ):
            scores["MACHINE_LEARNING"] += 3

        if (
            "research" in query
            or "latest" in query
            or "recent" in query
        ):
            scores["RESEARCH"] += 2


        if max(scores.values()) == 0:
            return "GENERAL"

        best_intent = max(
            scores,
            key=scores.get
        )

        return best_intent


    def signal_matches(
        self,
        query: str,
        signal: str
    ) -> bool:

        if " " in signal:
            return signal in query


        return bool(
            re.search(
                rf"\b{re.escape(signal)}\b",
                query
            )
        )

    def signal_weight(
        self,
        signal: str
    ) -> float:

        strong_signals = {

            "machine learning": 3.0,
            "machine-learning": 3.0,
            "ml model": 3.0,

            "data analysis": 3.0,

            "deep learning": 3.0,

            "research": 3.0,

            "debug": 2.5,

            "classification": 2.0,
            "regression": 2.0,

            "dataset": 1.5,

            "python": 1.5
        }

        return strong_signals.get(
            signal,
            1.0
        )

    def extract_goal(
        self,
        query: str
    ) -> str:

        patterns = [

            r"i want to (.+)",

            r"i need to (.+)",

            r"help me (.+)",

            r"how can i (.+)",

            r"how do i (.+)",

            r"can you (.+)",

            r"please (.+)"
        ]

        normalized = self.normalize(query)

        for pattern in patterns:

            match = re.search(
                pattern,
                normalized
            )

            if match:
                return match.group(1).strip()

        return query.strip()


    def extract_entities(
        self,
        query: str
    ) -> List[str]:

        entities = []

        for entity in self.known_entities:

            if self.signal_matches(
                query,
                entity
            ):
                entities.append(entity)

        return sorted(
            set(entities)
        )


    def extract_requirements(
        self,
        query: str
    ) -> List[str]:

        requirements = []

        for requirement, signals in (
            self.requirement_signals.items()
        ):

            for signal in signals:

                if self.signal_matches(
                    query,
                    signal
                ):

                    requirements.append(
                        requirement
                    )

                    break

        return requirements

    def detect_capabilities(
        self,
        query: str
    ) -> List[str]:

        capabilities = []

        for capability, signals in (
            self.intent_signals.items()
        ):

            matched = False

            for signal in signals:

                if self.signal_matches(
                    query,
                    signal
                ):
                    matched = True
                    break

            if matched:
                capabilities.append(
                    capability
                )

        return capabilities

    def extract_constraints(
        self,
        query: str
    ) -> List[str]:

        constraints = []

        patterns = [

            r"under\s+(\d+)",

            r"within\s+(\d+)",

            r"before\s+(.+)",

            r"after\s+(.+)",

            r"only\s+(.+)",

            r"without\s+(.+)",

            r"using\s+(.+)"
        ]

        for pattern in patterns:

            matches = re.findall(
                pattern,
                query
            )

            for match in matches:

                constraints.append(
                    str(match).strip()
                )

        return constraints


    def calculate_complexity(
        self,
        query: str,
        requirements: List[str],
        capabilities: List[str]
    ) -> float:

        score = 0.20

        words = query.split()


        if len(words) > 12:
            score += 0.10

        if len(words) > 25:
            score += 0.10


        if len(requirements) >= 2:
            score += 0.15

        if len(requirements) >= 3:
            score += 0.10


        if len(capabilities) >= 2:
            score += 0.10

        if len(capabilities) >= 3:
            score += 0.10


        multi_step_signals = [
            "and",
            "then",
            "after",
            "also",
            "first",
            "finally",
            "step"
        ]

        matches = sum(
            1
            for word in multi_step_signals
            if self.signal_matches(
                query,
                word
            )
        )

        score += min(
            matches * 0.05,
            0.15
        )


        if (
            "MACHINE_LEARNING" in capabilities
            and "optimization" in requirements
        ):
            score += 0.10

        return round(
            min(score, 1.0),
            2
        )


    def detect_tool_requirement(
        self,
        query: str
    ) -> bool:

        tool_signals = [

            "search",
            "latest",
            "recent",
            "current",
            "news",
            "internet",
            "website",
            "file",
            "dataset",
            "csv",
            "calculate"
        ]

        return any(
            self.signal_matches(
                query,
                signal
            )
            for signal in tool_signals
        )



    def select_agents(
        self,
        understanding: QueryUnderstanding
    ) -> List[str]:

        agents = []

        intent = understanding.intent

        requirements = (
            understanding.requirements
        )



        intent_agent_map = {

            "MACHINE_LEARNING":
                "MLAgent",

            "DATA_ANALYSIS":
                "DataAnalysisAgent",

            "CODING":
                "CodingAgent",

            "RESEARCH":
                "ResearchAgent",

            "REASONING":
                "ReasoningAgent"
        }

        primary_agent = intent_agent_map.get(
            intent
        )

        if primary_agent:
            agents.append(
                primary_agent
            )


        if "implementation" in requirements:

            if "CodingAgent" not in agents:

                agents.append(
                    "CodingAgent"
                )

        if "analysis" in requirements:

            if "DataAnalysisAgent" not in agents:

                agents.append(
                    "DataAnalysisAgent"
                )

        if "research" in requirements:

            if "ResearchAgent" not in agents:

                agents.append(
                    "ResearchAgent"
                )

        if "debugging" in requirements:

            if "CodingAgent" not in agents:

                agents.append(
                    "CodingAgent"
                )

        if (
            "explanation" in requirements
            or "comparison" in requirements
        ):

            if "ReasoningAgent" not in agents:

                agents.append(
                    "ReasoningAgent"
                )


        if "prediction" in requirements:

            if "MLAgent" not in agents:

                agents.append(
                    "MLAgent"
                )


        if understanding.complexity >= 0.60:

            agents.append(
                "CriticAgent"
            )


        if not agents:

            agents.append(
                "GeneralAgent"
            )

        # Remove duplicates
        return list(
            dict.fromkeys(agents)
        )


    def generate_reasoning(
        self,
        understanding: QueryUnderstanding,
        agents: List[str]
    ) -> List[str]:

        reasoning = []

        reasoning.append(
            f"Intent detected: "
            f"{understanding.intent}"
        )

        reasoning.append(
            f"Goal identified: "
            f"{understanding.goal}"
        )

        reasoning.append(
            f"Complexity score: "
            f"{understanding.complexity}"
        )

        if understanding.capabilities:

            reasoning.append(
                "Capabilities detected: "
                + ", ".join(
                    understanding.capabilities
                )
            )

        if understanding.requirements:

            reasoning.append(
                "Requirements detected: "
                + ", ".join(
                    understanding.requirements
                )
            )

        if understanding.entities:

            reasoning.append(
                "Entities detected: "
                + ", ".join(
                    understanding.entities
                )
            )

        reasoning.append(
            "Selected agents: "
            + ", ".join(agents)
        )

        if understanding.needs_tools:

            reasoning.append(
                "External tools may be required."
            )

        if understanding.needs_multiple_agents:

            reasoning.append(
                "Task requires coordinated "
                "multi-agent processing."
            )

        return reasoning


    def calculate_confidence(
        self,
        understanding: QueryUnderstanding,
        agents: List[str]
    ) -> float:

        confidence = 0.45


        if understanding.intent != "GENERAL":

            confidence += 0.20


        if understanding.requirements:

            confidence += 0.10

        if understanding.entities:

            confidence += 0.05


        if understanding.capabilities:

            confidence += 0.05


        if agents:

            confidence += 0.05

        # Multiple independent signals
        if len(
            understanding.capabilities
        ) >= 2:

            confidence += 0.05

        return round(
            min(confidence, 0.95),
            2
        )



def print_decision(
    decision: BrainDecision
):

    u = decision.understanding

    print("\n" + "=" * 70)

    print("INTELLIGENCE BRAIN v1.1")

    print("=" * 70)

    print(
        f"USER       : {u.original_query}"
    )

    print(
        f"Intent     : {u.intent}"
    )

    print(
        f"Goal       : {u.goal}"
    )

    print(
        f"Complexity : {u.complexity}"
    )

    print(
        f"Entities   : {u.entities}"
    )

    print(
        f"Requirements: {u.requirements}"
    )

    print(
        f"Capabilities: {u.capabilities}"
    )

    print(
        f"Tools      : {u.needs_tools}"
    )

    print(
        f"Multi-Agent: {u.needs_multiple_agents}"
    )

    print(
        f"Agents     : "
        f"{decision.recommended_agents}"
    )

    print(
        f"Confidence : "
        f"{decision.confidence}"
    )

    print("\nReasoning:")

    for step in decision.reasoning:

        print(
            f"  → {step}"
        )

def run_tests():

    brain = IntelligenceBrain()

    test_queries = [

        "hello",

        "write python code to analyze my dataset",

        "build a machine learning model and improve its accuracy",

        "research the latest AI developments",

        "debug my Python code",

        "analyze my CSV dataset",

        "explain neural networks",

        "compare TensorFlow and PyTorch",

        "build a machine learning model using Python",

        "analyze my dataset and build a machine learning model",

        "predict customer churn and improve model performance",

        "research latest AI models and compare them"
    ]

    print("\n")
    print("#" * 70)
    print("# INTELLIGENT MULTI-AGENT SYSTEM")
    print("# BRAIN v1.1 TEST SUITE")
    print("#" * 70)

    for query in test_queries:

        decision = brain.think(query)

        print_decision(
            decision
        )

if __name__ == "__main__":

    run_tests()